### PR TITLE
Update PyO3 to 0.22

### LINKED ISSUE #1250: Update PyO3 to 0.22.x
### What is the expected enhancement?

This is mostly a reminder that we need to update to 0.22.1 (or later) following https://pyo3.rs/v0.22.0/migration.html

### PR DESCRIPTION
**Pull request by IvanIsCoding**
Closes #1250

This depends on:
* `rust-numpy` releasing 0.22, which will happen soon. For the time being, we build from their Git main branch
* `py-clone` feature is enabled, if it is disabled too many things fail
* ~The update broke `iterators.rs`, I haven't had the time to fix so for this draft I just deleted support for slicing. Of course the final version will need to reintroduce it~ Slicing is now fixed
* ~We have 68 warnings! But hey it builds~  Warnings are fixed

I also profited from this PR to update `ndarray` and `ndarray-stats`.

For `py-clone` I think we should handle it in a future PR

### CODE REVIEW

**Comment by IvanIsCoding** [comment]
Ok, this is ready just pending https://github.com/PyO3/rust-numpy/pull/453. Although #1292 might break it because there are some deprecated methods.

**Comment by IvanIsCoding** [comment]
Ok this is ready to go

**Comment by IvanIsCoding** [comment]
I think there is a bug in PyO3 0.22.4 released today (https://github.com/PyO3/pyo3/blob/release-0.22/CHANGELOG.md). Our code compiles with 0.22.3 but fails with 0.22.4. We should probably merge this as is an open an issue?

```
error[E0605]: non-primitive cast: `for<'py> unsafe fn(pyo3::Python<'py>, *mut pyo3::ffi::PyObject) -> Result<*mut pyo3::ffi::PyObject, pyo3::PyErr> {PyDiGraph::__pymethod_clear__}` as `unsafe extern "C" fn(*mut pyo3::ffi::PyObject) -> i32`
   --> src/digraph.rs:295:1
    |
295 | #[pymethods]
    | ^^^^^^^^^^^^ invalid cast
    |
    = note: this error originates in the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0605]: non-primitive cast: `for<'py> unsafe fn(pyo3::Python<'py>, *mut pyo3::ffi::PyObject) -> Result<*mut pyo3::ffi::PyObject, pyo3::PyErr> {PyGraph::__pymethod_clear__}` as `unsafe extern "C" fn(*mut pyo3::ffi::PyObject) -> i32`
   --> src/graph.rs:191:1
    |
191 | #[pymethods]
    | ^^^^^^^^^^^^ invalid cast
    |
    = note: this error originates in the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0592]: duplicate definitions with name `__pymethod_clear__`
   --> src/digraph.rs:295:1
    |
295 | #[pymethods]
    | ^^^^^^^^^^^^
    | |
    | duplicate definitions for `__pymethod_clear__`
    | other definition for `__pymethod_clear__`
    |
    = note: this error originates in the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by IvanIsCoding** [comment]
It is confirmed 0.22.4 has a regression: https://github.com/PyO3/pyo3/issues/4616

We can bump to 0.22.5 once it is released.

**Review by mtreinish — APPROVED** [review]
Looks good, except for one small stray comment inline which I'll apply and re-approve for. Thanks for doing this. I agree we should update to 0.22.5 and remove py-clone in a follow-up PR.
